<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net461</TargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>Xarial.XCad.Examples.PMPage.CSharp</RootNamespace>
		<AssemblyName>PMPage</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Xarial.XCad.SolidWorks" Version="0.9.0-dev.5223" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Resources\xarial.png" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
	
</Project>